export const environment = {//ESTOS PARÁMETROS SON LOS QUE USAN CUANDO EL DESPLIEGUE DEL PROYECTO ESTA EN PRUEBAS O PRODCCIÓN.
  production: true,//ESTABLECE QUE LOS PARÁMETROS ASIGNADOS SI SERÁN PARA AMBIENTE DE PRUEBAS O PRODUCCIÓN.
  baseUrl: '/backendsigepsv10',//ESTE PARÁMETRO SE USA PARA EL EMPLEO DEL LLAMADO DE LOS SERVICIOS DE LOS CRUDS DE LOS REGISTROS (LISTAR, GUARDAR, CONSULTAR, MODIFICAR, ELIMINAR) U OTROS ESPECIALES CUANDO EL PROYECTO ESTA EN DESARROLLO.
  //baseUrl: 'http://187.77.248.89:8080/backendsigepsv10',//ESTE PARÁMETRO SE USA PARA EL EMPLEO DEL LLAMADO DE LOS SERVICIOS DE LOS CRUDS DE LOS REGISTROS (LISTAR, GUARDAR, CONSULTAR, MODIFICAR, ELIMINAR) U OTROS ESPECIALES CUANDO EL PROYECTO ESTA EN DESARROLLO.
  //baseUrlArchivosExternos: 'http://187.77.248.89:8080/backendsigepsv10',//ESTE PARÁMETRO SE USA PARA EL LLAMADO DE LOS ARCHIVOS COMO IMÁGENES O DOCUMENTOS Y SER MOSTRADOS Y VISUALIZADOS EN EL FRONTEND DE UN REPOSITORIO EXTERNO DEL SERVIDOR DE APLICACIONES CUANDO EL PROYECTO ESTA EN DESARROLLO.
  //urlServidorExpress: 'http://187.77.248.89:3000'//ESTE PARÁMETRO ES LA URL DEL SERVIDOR EXPRESS DEL SERVIDOR DE APLICACIONES CUANDO EL PROYECTO ESTA DESPLEGADO EN PRUEBAS O PRODUCCIÓN.
};
